version: '3'

networks:
  emission-inventory:
    driver: bridge

services:
  app: 
    image: node:latest
    container_name: emission-inventory
    restart: always
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - emission-inventory
    depends_on:
      - database
    env_file:
      - .env
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    command: bash -c "npm install && npm run start:dev"

  database: 
    image: mysql:latest
    container_name: emission-inventory-database
    restart: always
    volumes:
      - ./docker:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - emission-inventory
    ports:
      - "3306:3306"
    